command: ['streamlit', 'run', 'streamlit_multi_genie_tools.py']
env:
  - name: 'DATABRICKS_TOKEN'
    valueFrom: 'token'
  - name: 'DATABRICKS_HOST'
    valueFrom: 'DATABRICKS_HOST'
  - name: 'DATABRICKS_MODEL'
    valueFrom: 'DATABRICKS_MODEL'
  - name: 'GENIE_SPACE_STORE_PERFORMANCE_ID'
    valueFrom: 'GENIE_SPACE_STORE_PERFORMANCE_ID'
  - name: 'GENIE_SPACE_PRODUCT_INV_ID'
    valueFrom: 'GENIE_SPACE_PRODUCT_INV_ID'
  - name: 'MLFLOW_EXPERIMENT_ID'
    valueFrom: 'MLFLOW_EXPERIMENT_ID'