CATALOG: main
DATABRICKS_MODEL: databricks-claude-3-7-sonnet
GENIE_SPACE_PRODUCT_INV_ID: 01f04625344918f0bbe85c91888b4933
GENIE_SPACE_STORE_PERFORMANCE_ID: 01f04625347f1de2aec1515a10aa28ad
MLFLOW_EXPERIMENT_ID: "3369811628461668"
SCHEMA: genie_multi_tool
VECTOR_SEARCH_INDEX_NAME: main.genie_multi_tool.retail_code_of_conduct_index
