DATABRICKS_MODEL: "databricks-claude-3-7-sonnet"
GENIE_SPACE_STORE_PERFORMANCE_ID: "01f0408ecdfe1d2595651a15a88f909a"
GENIE_SPACE_PRODUCT_INV_ID: "01f0408efb0c19099ce7e958563c175a"
MLFLOW_EXPERIMENT_ID: "2933242203415883"
DATABRICKS_SERVING_ENDPOINT_NAME: "agents_mk_fiddles-genie_multi_agent-retail_code_of_conduct_bot"
VECTOR_SEARCH_ENDPOINT_NAME: "vector-search-multi-agent-genie"
VECTOR_SEARCH_INDEX_NAME: "mk_fiddles.genie_multi_agent.retail_code_of_conduct_index"