CATALOG: main
DATABRICKS_MODEL: databricks-claude-3-7-sonnet
GENIE_SPACE_PRODUCT_INV_ID: 01f0408efb0c19099ce7e958563c175a
GENIE_SPACE_STORE_PERFORMANCE_ID: 01f047c6e38a1ec9a9e2fbc37fa0fc30
MLFLOW_EXPERIMENT_ID: '4259706046556173'
SCHEMA: genie_multi_agent
